name: Push-to-Server

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cloud on main branch push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TARGETDIR: appgoblin
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: TARGETDIR
          script: |
            cd $TARGETDIR
            pwd
            git pull origin main
            sudo systemctl enable /home/goblin/appgoblin/scripts/appgoblin-api.service
            sudo systemctl enable /home/goblin/appgoblin/scripts/appgoblin-frontend.service
            sudo systemctl daemon-reload
            echo "Restart systemd backend"
            sudo systemctl restart appgoblin-api
            cd blog
            pwd
            echo "Build blog"
            npm install
            npm run build
            cd ../frontend
            pwd
            echo "Build and restart frontend"
            export PATH="/home/root/.nvm/versions/node/v22.13.1/bin:$PATH" && /home/goblin/.nvm/versions/node/v22.13.1/bin/npm run build && sudo systemctl restart appgoblin-frontend
